name: VSCode Extension

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  code_build:
    runs-on: windows-2019
    name: Build VSCode Extension
    env:
      VSIX_MAJOR: 0.1
    
    steps:
    - name: Checkout current repo
      uses: actions/checkout@v2
      with:
        path: main
        submodules: true

    - name: Checkout Meadow.CLI.Core side-by-side
      uses: actions/checkout@v2
      with:
        repository: WildernessLabs/Meadow.CLI
        path: Meadow.CLI
        ref: develop

    - name: Setup .NET Core 6.0.x and 7.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: | 
          6.0.x
          7.0.x

    - name: Setup Nuget
      uses: Nuget/setup-nuget@v1.0.5

    - name: Setup Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install NPM
      run: |
        cd main
        npm install
        npm update

    - name: Install vsce
      run: |
        npm i -g @vscode/vsce

    - name: Add MSBuild to Path
      uses: microsoft/setup-msbuild@v1.1

    - name: Restore and Build VSCode Extension
      run: |
        dotnet restore main/src/csharp/VSCodeMeadow.csproj /p:Configuration=Debug
        dotnet build main/src/csharp/VSCodeMeadow.csproj /p:Configuration=Debug

    - name: Build WebPack
      run: |
        cd main
        npm install -g webpack
        npm install -D ts-loader
        npm run webpack

    - if: ${{ github.ref != 'refs/heads/main' }}
      name: Build Pre-Release VSIX on non main branch
      run: |
        cd main
        vsce package --pre-release

    - if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      name: Build Release VSIX on main branch
      run: |
        cd main
        vsce package

    - name: Upload VSIX Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: VSCodeMeadow.vsix
        path: 'main/*.vsix'

    - if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      name: Publish VSCode Extension
      run: |
        cd main
        vsce publish -p ${{ secrets.MARKETPLACE_PUBLISH_PAT }}
