name: VSCode Extension
env:
  IDE_TOOLS_RELEASE_VERSION: 3.0.0

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-vscode:
    runs-on: windows-latest
    name: Build VSCode Extension

    steps:
    - name: Checkout current repo
      uses: actions/checkout@v7
      with:
        path: main

    - name: Checkout Meadow.Debugging side-by-side
      uses: actions/checkout@v7
      with:
        repository: WildernessLabs/Meadow.Debugging
        path: Meadow.Debugging
        ref: main
        submodules: true

    - name: Checkout Meadow.CLI side-by-side
      uses: actions/checkout@v7
      with:
        repository: WildernessLabs/Meadow.CLI
        path: Meadow.CLI
        ref: meadow-3.0

    - name: Checkout Meadow.Contracts side-by-side
      uses: actions/checkout@v7
      with:
        repository: WildernessLabs/Meadow.Contracts
        path: Meadow.Contracts
        ref: develop

    - name: Checkout Meadow.Units side-by-side
      uses: actions/checkout@v7
      with:
        repository: WildernessLabs/Meadow.Units
        path: Meadow.Units
        ref: develop

    - name: Checkout Meadow.Logging side-by-side
      uses: actions/checkout@v7
      with:
        repository: WildernessLabs/Meadow.Logging
        path: Meadow.Logging
        ref: develop

    - name: Setup .NET '8.0.x'
      uses: actions/setup-dotnet@v6
      with:
        dotnet-version: | 
          8.0.x
          10.0.x

    - name: Setup Nuget
      uses: nuget/setup-nuget@v3

    - name: Setup Node.js 24
      uses: actions/setup-node@v7
      with:
        node-version: 24

    - name: Install vsce
      run: |
        npm i -g @vscode/vsce
        npm i -g @vscode/debugprotocol

    - name: Install FallBack Sources
      run: |
        nuget install Microsoft.SymbolStore -Version 1.0.411401 -FallbackSource "https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json"

    - if: ${{ github.event_name == 'workflow_dispatch' }}
      name: Update VSCode Version Numbers
      run: |
        $content = Get-Content main/package.json | Out-String
        $newcontent = $content -replace '"version": "1.*",', '"version": "${{ENV.IDE_TOOLS_RELEASE_VERSION}}",'
        $newcontent | Set-Content main/package.json

    - name: Build Meadow.Debugging
      run: |
        dotnet restore Meadow.Debugging/Meadow.Debugging.sln
        dotnet build Meadow.Debugging/Meadow.Debugging.sln -c Debug --no-restore -p:TargetIDE=vscode

    - name: Build WebPack
      run: |
        cd main
        npm install -g webpack
        npm install -D ts-loader
        npm run webpack

    - if: ${{ github.ref != 'refs/heads/main' }}
      name: Build Pre-Release VSIX on non main branch
      run: |
        cd main
        vsce package --pre-release

    - if: ${{ github.ref == 'refs/heads/main' }}
      name: Build Release VSIX on main branch
      run: |
        cd main
        vsce package

    - name: Upload VSIX Artifacts
      uses: actions/upload-artifact@v7
      with:
        name: VSCodeMeadow.vsix.${{ ENV.IDE_TOOLS_RELEASE_VERSION }}
        path: 'main/*.vsix'

    - if: ${{ github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main' }}
      name: Publish VSCode Extension
      run: |
        cd main

        vsce publish -p ${{ secrets.MARKETPLACE_PUBLISH_PAT }}
